config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :characters
  resources :universes
  resources :abilities

  root "home#index"
end

app/models/ability.rb
class Ability < ActiveRecord::Base
  has_many :character_abilities
  has_many :characters, through: :character_abilities
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :universe
  has_many :character_abilities
  has_many :abilities, through: :character_abilities

  validates :hero_name, presence: true
  validates :hero_name, uniqueness: { case_sensitive: false }
  validates :universe, presence: true
end

app/models/character_ability.rb
class CharacterAbility < ActiveRecord::Base
  belongs_to :character
  belongs_to :ability
end

app/models/universe.rb
class Universe < ActiveRecord::Base
  has_many :characters
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_ability, only: [:show, :edit, :update, :destroy]

  def index
    @abilities = Ability.all
  end

  def show
  end

  def new
    @ability = Ability.new
  end

  def create
    @ability = Ability.new(abilities_params)

    if @ability.save
      redirect_to ability_path(@ability), notice: "Ability was successfully created"
    else
      flash.now[:error] = "An error occurred when saving this Ability"
      render :new
    end
  end

  def edit
  end

  def update
    if @ability.update(abilities_params)
      redirect_to ability_path(@ability), notice: "Ability was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this Ability"
      render :edit
    end
  end

  def destroy
    @ability.destroy

    redirect_to abilities_path, notice: "Ability was successfully deleted"
  end

  private

  def find_ability
    @ability = Ability.find(params[:id])
  end

  def abilities_params
    params.require(:ability).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_character, only: [:show, :edit, :update, :destroy]

  def index
    @characters = Character.all
  end

  def show
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      flash[:notice] = "Character was successfully created"
      redirect_to character_path(@character)
    else
      flash.now[:error] = "An error occurred while saving this character"
      render :new
    end
  end

  def edit
  end

  def update
    if @character.update(character_params)
      redirect_to character_path(@character), notice: "Character was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this Character"
      render :edit
    end
  end

  def destroy
    @character.destroy

    redirect_to characters_path, notice: "Character was successfully deleted"
  end

  private

  def find_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:first_name, :last_name, :hero_name, :universe_id, :bio, :ability_ids => [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_universe, only: [:show, :edit, :update, :destroy]
  
  def index
    @universes = Universe.all
  end

  def show
  end

  def new
    @universe = Universe.new
  end

  def create
    @universe = Universe.new(universe_params)

    if @universe.save
      flash[:notice] = "Character was successfully created"
      redirect_to universe_path(@universe)
    else
      flash.now[:error] = "An error occurred while saving this universe"
      render :new
    end
  end

  def edit
  end

  def update
    if @universe.update(universe_params)
      redirect_to universe_path(@universe), notice: "Universe was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this Universe"
      render :edit
    end
  end

  def destroy
    @universe.destroy

    redirect_to universes_path, notice: "Universe was successfully deleted"
  end

  private

  def find_universe
    @universe = Universe.find(params[:id])
  end

  def universe_params
    params.require(:universe).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abilities/_form.html.erb
<%= form_for @ability do |f| %>

  <% if @ability.errors.any? %>
    <% @ability.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/abilities/edit.html.erb
<h1>Edit Ability</h1>

<%= link_to "Back to Abilities List", abilities_path %>

<%= render 'form' %>

app/views/abilities/index.html.erb
<h1>Abilities</h1>
<%= link_to "Home", root_path %>
<% if current_user %>
  <%= link_to "Create New Ability", new_ability_path %>
<% end %>

<br />
<br />
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
  <tbody>
    <% @abilities.each do |ability| %>
      <tr>
        <td><%= link_to(ability.name, ability_path(ability)) %></td>
        <% if current_user %>
          <td><%= link_to "edit", edit_ability_path(ability) %></td>
          <td><%= link_to "delete", ability_path(ability), method: :delete, data: {confirm: "Are you sure you want to delete this ability?"}%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/abilities/new.html.erb
<h1>New Ability</h1>

<%= link_to "Back to Abilities List", abilities_path %>

<%= render 'form' %>

app/views/abilities/show.html.erb
<%= link_to "Back to Abilities List", abilities_path %>

<p>
  <strong>Ability Name:</strong> <%= @ability.name %>
</p>

<br />
<td><%= link_to "edit", edit_ability_path(@ability) %></td>

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>

  <% if @character.errors.any? %>
    <% @character.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :hero_name %><br>
    <%= f.text_field :hero_name %>
  </p>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </p>

  <p>
    <%= f.label :universe %><br>
    <%= collection_select(:character, :universe_id, Universe.all, :id, :name, include_blank: true) %>
  </p>

  <p>
    <%= f.label :ability, "Ablilities" %><br>
    
    <%= collection_check_boxes(:character, :ability_ids, Ability.all, :id, :name) %>
  </p>


  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h1>Hero App</h1>

<p>Characters <%= link_to "View Characters", characters_path %></p>
<p>Abilities <%= link_to "View Abilities", abilities_path %></p>
<p>Universes <%= link_to "View Universes", universes_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeroApp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav>
      <% if current_user %>
        <%= current_user.email %>
        <%= link_to "sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "register", new_user_registration_path %>
        <%= link_to "sign in", user_session_path %>
      <% end %> 
    </nav>

    <% flash.each do |name, msg| %>
      <div class="<%= name %>">
        <%= msg %>
      </div>
    <% end %>


    <%= yield %>

  </body>
</html>

app/views/universes/_form.html.erb
<%= form_for @universe do |f| %>

  <% if @universe.errors.any? %>
    <% @universe.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/universes/edit.html.erb
<h1>Edit Universe</h1>

<%= link_to "Back to Universe List", universes_path %>

<%= render 'form' %>

app/views/universes/index.html.erb
<h1>Universes</h1>
<%= link_to "Home", root_path %>
<% if current_user %>
  <%= link_to "Create New Universe", new_universe_path %>
<% end %>
<br />
<br />
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
  <tbody>
    <% @universes.each do |universe| %>
      <tr>
        <td><%= link_to(universe.name, universe_path(universe)) %></td>

        <% if current_user %>
          <td><%= link_to "edit", edit_universe_path(universe) %></td>
          <td><%= link_to "delete", universe_path(universe), method: :delete, data: {confirm: "Are you sure you want to delete this universe?"}%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/universes/new.html.erb
<h1>New Universe</h1>

<%= link_to "Back to Universe List", universes_path %>

<%= render 'form' %>

app/views/universes/show.html.erb
<%= link_to "Back to Universe List", universes_path %>

<p>
  <strong>Universe Name:</strong> <%= @universe.name %>
</p>

<br />
<% if current_user %>
  <td><%= link_to "edit", edit_universe_path(@universe) %></td>
<% end %>